# Generated by Django 4.2.4 on 2023-08-24 15:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuclearReactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=97)),
                ('name_en', models.CharField(max_length=80)),
                ('outp_mw', models.IntegerField(max_length=10)),
                ('mpoly', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
        ),
    ]
